[package]
name       = "ccs"
version    = "0.4.3"
edition    = "2021"
license    = "0BSD"
repository = "https://github.com/museun/ccs"

[dependencies]
anstream   = "0.2.6"
anyhow     = "1.0.70"
gumdrop    = "0.8.1"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
serde      = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
