[package]
name = "ccs"
version = "0.4.0"
edition = "2021"
license = "0BSD"
repository = "https://github.com/museun/ccs"

[dependencies]
anyhow = "1.0.59"
gumdrop = "0.8.1"
regex = "1.6.0"
yansi = "0.5.1"
