[package]
name       = "ccs"
version    = "0.6.0"
edition    = "2021"
license    = "0BSD"
repository = "https://github.com/museun/ccs"

[dependencies]
anstream    = "0.2.6"
anyhow      = "1.0.70"
bpaf        = { version = "0.7.10", features = ["derive"] }
directories = "5.0.0"
owo-colors  = { version = "3.5.0", features = ["supports-colors"] }
serde       = { version = "1.0.159", features = ["derive"] }
serde_json  = "1.0.95"
toml        = "0.7.3"
